import assert from 'node:assert/strict'
import { createHash, createHmac } from 'node:crypto'
import test from 'node:test'
import { buildPublicServedAttestation } from './build-annual-public-served-attestation.mjs'

const privateKey = 'private-admission-test-key'; const publicKey = 'public-served-test-key'; const privateSha = 'a'.repeat(40); const deployedSha = '5'.repeat(40); const publicSha = 'b'.repeat(40)
const digest = (value) => `sha256:${createHash('sha256').update(value).digest('hex')}`; const sign = (key, value) => createHmac('sha256', key).update(digest(JSON.stringify(value))).digest('hex')
const sourceArtifact = { repository: 'silent-suite/silentsuite-internal', runId: 918273645, runAttempt: 2, artifactId: 881, name: 'annual-only-pre-public-admission-918273645-2' }; const run = { runId: 123456789, runAttempt: 3 }; const artifact = { repository: 'silent-suite/silentsuite', runId: run.runId, runAttempt: run.runAttempt, artifactId: 774 }
const deployedRuntime = { privateSha: deployedSha, imageDigest: `sha256:${'c'.repeat(64)}`, phase: 'additive', deployedAt: '2026-08-30T10:00:00Z', observedAt: '2026-08-31T09:00:00Z', reobservedAt: '2026-08-31T09:00:05Z' }
function admissionBytes(mutate = (value) => value) { const reviewUnsigned = { schemaVersion: 2, predicateType: 'https://silentsuite.io/attestations/annual-only-public-review/v2', repository: 'silent-suite/silentsuite', publicSha, runId: 44, runAttempt: 2, disclosureDigest: `sha256:${'2'.repeat(64)}` }; const review = { ...reviewUnsigned, signature: sign(privateKey, reviewUnsigned) }; const unsigned = mutate({ schemaVersion: 2, predicateType: 'https://silentsuite.io/attestations/annual-only-pre-public-admission/v2', privateSha, expectedPublicSha: publicSha, billingImageDigest: `sha256:${'c'.repeat(64)}`, rollbackImageDigest: `sha256:${'d'.repeat(64)}`, buildAttestationDigest: `sha256:${'e'.repeat(64)}`, qaAttestationDigest: `sha256:${'f'.repeat(64)}`, providerRegistryDigest: `sha256:${'1'.repeat(64)}`, providerAdmission: { artifactId: 88, archiveDigest: `sha256:${'3'.repeat(64)}`, statementDigest: `sha256:${'4'.repeat(64)}`, runId: 33368609150, runAttempt: 1 }, disclosureDigest: `sha256:${'2'.repeat(64)}`, producerRun: { runId: sourceArtifact.runId, runAttempt: sourceArtifact.runAttempt }, deployedRuntime, publicReview: review }); return Buffer.from(`${JSON.stringify({ ...unsigned, signature: sign(privateKey, unsigned) })}\n`) }
function build(overrides = {}) { return buildPublicServedAttestation({ admissionBytes: admissionBytes(), expectedPublicSha: publicSha, expectedSourcePrivateSha: privateSha, expectedSourceArtifact: sourceArtifact, expectedPublicRepository: 'silent-suite/silentsuite', privateAdmissionHmacKey: privateKey, publicReviewHmacKey: privateKey, publicServedHmacKey: publicKey, publicDeploymentRun: run, publicArtifact: artifact, publicArtifactName: 'annual-only-public-served-attestation-123456789-3', deploymentVerified: true, clientServedAt: '2026-08-11T12:00:05Z', now: () => '2026-08-11T12:00:06Z', ...overrides }) }
test('mints a closed canonical v2 Stage B carrying the producer run and the separately bound deployed runtime only after fresh service checks', () => {
  const { attestation, bytes } = build()
  assert.deepEqual(Object.keys(attestation), ['schemaVersion', 'predicateType', 'privateSha', 'publicSha', 'privateAdmissionDigest', 'billingImageDigest', 'disclosureDigest', 'deployedRuntime', 'producerRun', 'publicDeploymentRun', 'publicArtifact', 'clientServedAt', 'verifiedAt', 'signature'])
  assert.equal(attestation.schemaVersion, 2); assert.equal(attestation.predicateType, 'https://silentsuite.io/attestations/annual-only-public-served/v2')
  assert.equal(attestation.privateSha, privateSha); assert.deepEqual(attestation.deployedRuntime, deployedRuntime); assert.deepEqual(attestation.producerRun, { runId: sourceArtifact.runId, runAttempt: sourceArtifact.runAttempt })
  assert.equal(attestation.privateAdmissionDigest, digest(admissionBytes())); assert.equal(attestation.clientServedAt, '2026-08-11T12:00:05Z'); assert.equal(attestation.verifiedAt, '2026-08-11T12:00:06Z'); assert.equal(bytes.toString(), `${JSON.stringify(attestation)}\n`)
  assert.equal('privateDeploymentRun' in attestation, false)
})
test('rejects a retired v1 admission, before-deploy, wrong SHA/artifact/name, mutable run identity, and timestamp-order fabrication', () => {
  assert.throws(() => build({ admissionBytes: admissionBytes((value) => { const legacy = { ...value, schemaVersion: 1, predicateType: 'https://silentsuite.io/attestations/annual-only-pre-public-admission/v1', privateDeploymentRun: value.producerRun }; delete legacy.producerRun; delete legacy.deployedRuntime; return legacy }) }), /v1 is retired/i)
  assert.throws(() => build({ deploymentVerified: false }), /after verified Web and Docs deployment/i); assert.throws(() => build({ clientServedAt: undefined }), /client timestamp/i); assert.throws(() => build({ clientServedAt: '2026-08-11T12:00:07Z' }), /timestamp order/i); assert.throws(() => build({ expectedPublicSha: 'f'.repeat(40) }), /exact public SHA/i); assert.throws(() => build({ expectedSourcePrivateSha: deployedSha }), /private SHA/i); assert.throws(() => build({ publicArtifact: { ...artifact, repository: 'silent-suite/attacker' } }), /public artifact/i); assert.throws(() => build({ publicArtifact: { ...artifact, runAttempt: 4 } }), /public artifact/i); assert.throws(() => build({ publicArtifactName: 'annual-only-public-served-attestation-main' }), /artifact name/i); assert.throws(() => build({ publicDeploymentRun: { runId: 0, runAttempt: 3 } }), /deployment run/i)
})
